services:
  app:
    build: ./
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - SURREAL_URI=ws://surrealdb:9000/rpc
      - NODE_ENV=production
    networks:
      - surrealdb-net
      - dokploy-network
    labels:
      - traefik.http.routers.realcoin-frontend-e1fdpz-1-web.rule=Host(`realcoin.tally.gay`)
      - traefik.http.routers.realcoin-frontend-e1fdpz-1-web.entrypoints=web
      - traefik.http.services.realcoin-frontend-e1fdpz-1-web.loadbalancer.server.port=8080
      - traefik.http.routers.realcoin-frontend-e1fdpz-1-web.service=realcoin-frontend-e1fdpz-1-web
      - traefik.docker.network=dokploy-network
      - traefik.enable=true
networks:
  surrealdb-net:
    external: true
  dokploy-network:
    external: true
